### ISSUE TITLE
在iPad上使用，在笔记本上只能看到部分屏幕，且操控错位

### ISSUE THREAD

**Issue by evoke322** [OwnGoalStudio/TrollVNC#15]
如题，显示效果如下所示，请作者检查一下，或者请教一下应该怎么设置

iPad显示如图：
<img width="2388" height="1668" alt="Image" src="https://github.com/user-attachments/assets/e61a9905-ac3f-44f1-bfdc-1b97b2d512aa" />
PC端显示如图
<img width="815" height="1201" alt="Image" src="https://github.com/user-attachments/assets/d7fd2cc5-8ec0-4391-b34e-301bb741ec1c" />

**Comment by Lessica** [comment]
Fixed in [v3.1-2](https://github.com/OwnGoalStudio/TrollVNC/releases/tag/v3.1-2)

**Comment by waruhachi** [comment]
> Fixed in [v3.1-2](https://github.com/OwnGoalStudio/TrollVNC/releases/tag/v3.1-2)

I have an iPad (6th Generation) on iOS 14.8, and the fix does not seem to fix the issue. Is there anything I can do or provide to help debug this issue?

**Comment by Lessica** [comment]
> > Fixed in [v3.1-2](https://github.com/OwnGoalStudio/TrollVNC/releases/tag/v3.1-2)
> 
> I have an iPad (6th Generation) on iOS 14.8, and the fix does not seem to fix the issue. Is there anything I can do or provide to help debug this issue?

There's an option to toggle the fix.

**Comment by waruhachi** [comment]
> > > Fixed in [v3.1-2](https://github.com/OwnGoalStudio/TrollVNC/releases/tag/v3.1-2)
> > 
> > 
> > I have an iPad (6th Generation) on iOS 14.8, and the fix does not seem to fix the issue. Is there anything I can do or provide to help debug this issue?
> 
> There's an option to toggle the fix.

Yes, I tried that. It did not fix the orientation issue. I just made some hardcoded changes to the source to fix my device.

**Comment by Lessica** [comment]
> > > > Fixed in [v3.1-2](https://github.com/OwnGoalStudio/TrollVNC/releases/tag/v3.1-2)
> > > 
> > > 
> > > I have an iPad (6th Generation) on iOS 14.8, and the fix does not seem to fix the issue. Is there anything I can do or provide to help debug this issue?
> > 
> > 
> > There's an option to toggle the fix.
> 
> Yes, I tried that. It did not fix the orientation issue. I just made some hardcoded changes to the source to fix my device.

That fix works on my iPad models:
- iPad mini 6 (iOS 16)
- iPad 7 (iOS 18)

Describe your findings more clearly or submit a PR instead.

**Comment by waruhachi** [comment]
> > > > > Fixed in [v3.1-2](https://github.com/OwnGoalStudio/TrollVNC/releases/tag/v3.1-2)
> > > > 
> > > > 
> > > > I have an iPad (6th Generation) on iOS 14.8, and the fix does not seem to fix the issue. Is there anything I can do or provide to help debug this issue?
> > > 
> > > 
> > > There's an option to toggle the fix.
> > 
> > 
> > Yes, I tried that. It did not fix the orientation issue. I just made some hardcoded changes to the source to fix my device.
> 
> That fix works on my iPad models:
> 
> * iPad mini 6 (iOS 16)
> * iPad 7 (iOS 18)
> 
> Describe your findings more clearly or submit a PR instead.

Here are the changes: https://github.com/OwnGoalStudio/TrollVNC/compare/main...waruhachi:TrollVNC:main

These changes were made with the assistance of AI, as I do not fully understand the codebase and details of VNC, but they were able to make my device work.
